a = input('Digite Qualquer coisa: ')
print('O tipo primitivo do valor digitado é: {}' .format(type(a)))
print('Só tem espaço: {}' .format(a.isspace()))
print('É um número: {}' .format(a.isnumeric()))
print('É alfabético: {}' .format(a.isalpha()))
print('É alfanumérico: {}' .format(a.isalnum()))
print('Está em mausculas: {}' .format(a.isupper()))
print('Está em minusculas: {}' .format(a.islower()))
print('Está capitalizado: {}' .format(a.istitle()))
