times = ('Botafogo', 'Atlético-MG', 'Bragantino', 'Bahia', 'Flamengo', 'Athletico-PR', 'Grêmio', 'Internacional', 'Criciúma', 'Fluminense', 'Cruzeiro', 'Fortaleza', 'Palmeiras', 'Juventude', 'São Paulo', 'Vasco', 'Vitória', 'Corinthians', 'Atlético-GO', 'Cuiabá')
print('-=-'*20)
print(times)
print('-=-'*20)
print(f'Os cincos primeiros colocados são:{times[0:5]}')
print('-=-'*20)
print(f'Os ultimos quatros colocados são: {times[16:]}')
print('-=-'*20)
print(f'A lista em ordem alfabética é: {sorted(times)}')
print('-=-'*20)
print(f'O vasco entá na posição: {times.index("Vasco")}')
