listagem = ('Smartphone XYZ', 1500.00, 'Laptop ABC', 3000.00, 'Fones de Ouvido Bluetooth', 200.00, 'Mochila Resistente para Notebook', 150.00, 'Smartwatch', 400.00, 'Livro', 50.00, ' Câmera Fotográfica Compacta', 800.00, 'Conjunto de Panelas Antiaderentes', 300.00, 'Kit de Ferramentas Domésticas', 100.00,)
print('-'*50)
print('LISTAGEM DE PRODUDO')
print('-'*50)
print(f'Smartphone XYZ................R$: {listagem[1]:.2f}')
print(f'Laptop ABC....................R$: {listagem[3]:.2f}')
print(f'Fones de Ouvido Bluetooth.....R$: {listagem[5]:.2f}')
print(f'Mochila Resistente para Notebook.......R$: {listagem[7]:.2f}')
print(f'Smartwatch....................R$: {listagem[9]:.2f}')
print(f'Livro.........................R$: {listagem[11]:.2f}')
print(f'Câmera Fotográfica Compacta............R$: {listagem[13]:.2f}')
print(f'Conjunto de Panelas Antiaderentes.......R$: {listagem[15]:.2f}')
print(f'Kit de Ferramentas Domésticas...........R$: {listagem[17]:.2f}')
print('-'*50)
